upstream rentify_api {
    server web:8000;
}

server {
    listen 80;
    server_name rentify.kz; # Замени на свой домен

    client_max_body_size 20M;

    location / {
        proxy_pass http://rentify_api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Обслуживание статики Django (админка и т.д.)
    location /static/ {
        alias /app/static/;
    }

    # Обслуживание медиа (фото инструментов)
    location /media/ {
        alias /app/media/;
    }

    # Безопасность: запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
    }
}
